-- Reference schema for Laravel migration implementation.
CREATE TABLE users (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, username VARCHAR(80) UNIQUE NOT NULL, email VARCHAR(190) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, avatar_url TEXT, bio TEXT, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL);
CREATE TABLE countries (id BIGSERIAL PRIMARY KEY, name VARCHAR(160) NOT NULL, iso2 CHAR(2) UNIQUE NOT NULL, iso3 CHAR(3) UNIQUE, continent VARCHAR(80), geojson_key VARCHAR(160));
CREATE TABLE districts (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, division VARCHAR(100), geojson_key VARCHAR(160) UNIQUE);
CREATE TABLE user_countries (user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, country_id BIGINT REFERENCES countries(id) ON DELETE CASCADE, visited_at DATE NULL, notes TEXT, PRIMARY KEY(user_id,country_id));
CREATE TABLE user_districts (user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, district_id BIGINT REFERENCES districts(id) ON DELETE CASCADE, visited_at DATE NULL, notes TEXT, PRIMARY KEY(user_id,district_id));
CREATE TABLE trips (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, title VARCHAR(180) NOT NULL, start_date DATE, end_date DATE, budget NUMERIC(12,2), currency CHAR(3) DEFAULT 'BDT', status VARCHAR(30) DEFAULT 'draft', created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL);
CREATE TABLE places (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, name VARCHAR(180) NOT NULL, district_id BIGINT REFERENCES districts(id) ON DELETE SET NULL, description TEXT, latitude DECIMAL(10,7), longitude DECIMAL(10,7), status VARCHAR(30) DEFAULT 'pending', created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL);
CREATE TABLE reviews (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, place_id BIGINT REFERENCES places(id) ON DELETE CASCADE, rating SMALLINT CHECK(rating BETWEEN 1 AND 5), body TEXT, status VARCHAR(30) DEFAULT 'published', created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL);
CREATE TABLE badges (id BIGSERIAL PRIMARY KEY, code VARCHAR(80) UNIQUE NOT NULL, name VARCHAR(120) NOT NULL, description TEXT);
CREATE TABLE user_badges (user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, badge_id BIGINT REFERENCES badges(id) ON DELETE CASCADE, awarded_at TIMESTAMP, PRIMARY KEY(user_id,badge_id));
